# (PART\*) Quantitative Research {-}

# Introduction

For an introduction to conducting and evaluating quantitative research, you can watch this video:
`r video_code("sM7z8YoFLDo")`

## Key concepts

If you understand the following concepts, you will be in a good place to understand and assess quantitative research:

- **Hypothesis testing:** quantitative research aims to develop hypotheses and then check whether new data is consistent with these hypotheses. This sequence matters particularly for inferential statistics, i.e. for knowing how to determine whether a certain pattern in the data is likely to arise due to random variation between samples we look at, or due to a real difference in the population of interest.

- **Experiments with randomisation and blinding**. In essence, the idea is that if participants are randomly allocated to groups, the only difference between the groups is what happens during the experiment. If there is adequate blinding (i.e. experimenters and participants do not know what condition they are assigned to), the only difference is that of interest (e.g., the content of a pill). Otherwise, experimenter and participant expectations will also differ, which might change results. You might want to have a look at this [detailed but brief discussion of blinding](https://s4be.cochrane.org/blog/2017/06/26/blinding-comprehensive-guide-students/){target="_blank"}
  
- **Correlational/observational studies** and their inability to show causality: observational studies can be great to describe reality and to highlight associations, but without experiments (or more complex designs that aim to approximate experiments), we must be careful not to confuse correlation (co-occurrence of two variable) with causation (causal dependence of one on the other).

- **Validity**
    - **Internal validity**: degree to which a study can rule out alternative explanations for the effects observed, apart from those highlighted by the researchers. This is most concerning in experimental research. A list of things that might reduce internal validity can be found [here](https://researchbasics.education.uconn.edu/experimental-_research/){target="_blank"}
    - **External and ecological validity:** all about generalizability of results. External validity concerns generalisation to other participants, while ecological validity concerns the generalisation to real situations of interest. Detailed notes [here](https://researchbasics.education.uconn.edu/external_validity/#){target="_blank"}
  